# Generated by Django 3.2 on 2021-11-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_alter_query_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='event_category',
            field=models.CharField(choices=[('1', 'aras'), ('2', 'process'), ('3', 'network'), ('4', 'file'), ('5', 'registry'), ('6', 'authentication'), ('7', 'configuration'), ('8', 'database'), ('9', 'driver'), ('10', 'host'), ('11', 'iam'), ('12', 'intrusion_detection'), ('13', 'malware'), ('14', 'package'), ('15', 'session'), ('16', 'threat'), ('17', 'web')], default='1', max_length=32),
        ),
        migrations.AlterField(
            model_name='query',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='rule.rule'),
        ),
    ]
