# Generated by Django 3.2 on 2021-11-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0003_auto_20211114_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='event_category',
            field=models.CharField(choices=[('1', 'any'), ('2', 'process'), ('3', 'network'), ('4', 'file'), ('5', 'registry'), ('6', 'authentication'), ('7', 'configuration'), ('8', 'database'), ('9', 'driver'), ('10', 'host'), ('11', 'iam'), ('12', 'intrusion_detection'), ('13', 'malware'), ('14', 'package'), ('15', 'session'), ('16', 'threat'), ('17', 'web')], default='1', max_length=32),
        ),
    ]
