# Generated by Django 3.2 on 2021-11-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0004_alter_query_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='event_category',
            field=models.CharField(max_length=32),
        ),
    ]
