# Generated by Django 3.2 on 2021-11-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0005_alter_query_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='event_category',
            field=models.CharField(choices=[('any', 'any'), ('process', 'process'), ('network', 'network'), ('file', 'file'), ('registry', 'registry'), ('authentication', 'authentication'), ('configuration', 'configuration'), ('database', 'database'), ('driver', 'driver'), ('host', 'host'), ('iam', 'iam'), ('intrusion_detection', 'intrusion_detection'), ('malware', 'malware'), ('package', 'package'), ('session', 'session'), ('threat', 'threat'), ('web', 'web')], default='any', max_length=32),
        ),
    ]
